config {
    type: "table",
    schema: "dataform_sources",
}

SELECT
    event_timestamp,
    user_pseudo_id,
    ${c_functions.getEventParam('page_location')},
    ${c_functions.getEventParam('page_title')},
    ${c_functions.getEventParam('page_referrer')},
    ${c_functions.getEventParam('ga_session_id', 'int')},
    ${c_functions.getEventParam('entrances', 'int')},
FROM
    ${ref(constants.GA4_TABLE)}
WHERE
    event_name = 'page_view'
ORDER BY
    event_timestamp
